# Generated by Django 6.0.3 on 2026-04-04 16:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_unit', models.CharField(help_text='Unit of measurement (e.g., Nos, Kg, Ltr, Mtr)', max_length=50)),
                ('est_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimated Price')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Item Group',
                'verbose_name_plural': 'Item Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=200, unique=True)),
                ('total_semesters', models.PositiveIntegerField(help_text='Total number of semesters in this trade', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['trade_name'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='inventory.trade')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_date', models.DateField()),
                ('supplier_name', models.CharField(max_length=300)),
                ('item_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity Received')),
                ('bill_no', models.CharField(max_length=100, verbose_name='Bill Number')),
                ('financial_year', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031'), ('2031-2032', '2031-2032'), ('2032-2033', '2032-2033'), ('2033-2034', '2033-2034'), ('2034-2035', '2034-2035'), ('2035-2036', '2035-2036')], help_text='e.g., 2025-2026', max_length=9)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpr_entries', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Goods Purchase Register (GPR)',
                'verbose_name_plural': 'Goods Purchase Register (GPR)',
                'ordering': ['-inward_date'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.itemgroup'),
        ),
        migrations.CreateModel(
            name='ModelIndent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('semester_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semester Number')),
                ('financial_year', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031'), ('2031-2032', '2031-2032'), ('2032-2033', '2032-2033'), ('2033-2034', '2033-2034'), ('2034-2035', '2034-2035'), ('2035-2036', '2035-2036')], help_text='e.g., 2025-2026', max_length=9)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MERGED', 'Merged'), ('PURCHASED', 'Purchased'), ('ISSUED', 'Issued')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indents', to='inventory.instructor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indents', to='inventory.item')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indents', to='inventory.trade')),
            ],
            options={
                'verbose_name': 'Model Indent',
                'verbose_name_plural': 'Model Indents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_date', models.DateField()),
                ('opening_bal', models.PositiveIntegerField(default=0, verbose_name='Opening Balance')),
                ('out_qty', models.PositiveIntegerField(default=0, verbose_name='Quantity Issued')),
                ('current_bal', models.PositiveIntegerField(default=0, verbose_name='Current Balance')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_entries', to='inventory.instructor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_entries', to='inventory.item')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_entries', to='inventory.trade')),
            ],
            options={
                'verbose_name': 'Consumable Register (CR)',
                'verbose_name_plural': 'Consumable Register (CR)',
                'ordering': ['-inward_date'],
            },
        ),
    ]
