# Generated by Django 6.0.3 on 2026-04-04 17:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semester Number')),
                ('financial_year', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031'), ('2031-2032', '2031-2032'), ('2032-2033', '2032-2033'), ('2033-2034', '2033-2034'), ('2034-2035', '2034-2035'), ('2035-2036', '2035-2036')], help_text='e.g., 2025-2026', max_length=9)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MERGED', 'Merged'), ('PURCHASED', 'Purchased'), ('ISSUED', 'Issued')], default='DRAFT', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Optional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_notes', to='inventory.instructor')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_notes', to='inventory.trade')),
            ],
            options={
                'verbose_name': 'Demand Note',
                'verbose_name_plural': 'Demand Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_items', to='inventory.item')),
                ('demand_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.demandnote')),
            ],
            options={
                'verbose_name': 'Demand Item',
                'verbose_name_plural': 'Demand Items',
                'ordering': ['id'],
                'unique_together': {('demand_note', 'item')},
            },
        ),
    ]
