# Generated by Django 6.0.3 on 2026-04-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_demandnote_demanditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumableregister',
            options={'ordering': ['-inward_date', 'register_no', 'page_no', 'item_no', 'sub_entry'], 'verbose_name': 'Consumable Register (CR)', 'verbose_name_plural': 'Consumable Register (CR)'},
        ),
        migrations.AlterModelOptions(
            name='gpr',
            options={'ordering': ['-inward_date', 'register_no', 'page_no', 'item_no', 'sub_entry'], 'verbose_name': 'Goods Purchase Register (GPR)', 'verbose_name_plural': 'Goods Purchase Register (GPR)'},
        ),
        migrations.AddField(
            model_name='consumableregister',
            name='item_no',
            field=models.PositiveIntegerField(default=1, verbose_name='Item Index'),
        ),
        migrations.AddField(
            model_name='consumableregister',
            name='page_no',
            field=models.PositiveIntegerField(default=1, verbose_name='Page No'),
        ),
        migrations.AddField(
            model_name='consumableregister',
            name='register_no',
            field=models.PositiveIntegerField(default=1, verbose_name='CR Register No'),
        ),
        migrations.AddField(
            model_name='consumableregister',
            name='sub_entry',
            field=models.PositiveIntegerField(default=1, verbose_name='Sub Entry'),
        ),
        migrations.AddField(
            model_name='gpr',
            name='item_no',
            field=models.PositiveIntegerField(default=1, verbose_name='Item Index'),
        ),
        migrations.AddField(
            model_name='gpr',
            name='page_no',
            field=models.PositiveIntegerField(default=1, verbose_name='Page No'),
        ),
        migrations.AddField(
            model_name='gpr',
            name='register_no',
            field=models.PositiveIntegerField(default=1, verbose_name='GPR Register No'),
        ),
        migrations.AddField(
            model_name='gpr',
            name='sub_entry',
            field=models.PositiveIntegerField(default=1, verbose_name='Sub Entry'),
        ),
    ]
