# Generated by Django 6.0.3 on 2026-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_consumableregister_options_alter_gpr_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpr',
            name='gpr_no',
            field=models.CharField(default='GPR-000', max_length=100, verbose_name='GPR Number'),
        ),
        migrations.AlterField(
            model_name='gpr',
            name='register_no',
            field=models.PositiveIntegerField(default=1, verbose_name='Register No'),
        ),
    ]
