# Generated by Django 6.0.3 on 2026-04-05 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_gpr_gpr_no_alter_gpr_register_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimateQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_no', models.CharField(help_text='e.g., UQ-2025-0001', max_length=50, unique=True, verbose_name='Query Number')),
                ('financial_year', models.CharField(choices=[('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031'), ('2031-2032', '2031-2032'), ('2032-2033', '2032-2033'), ('2033-2034', '2033-2034'), ('2034-2035', '2034-2035'), ('2035-2036', '2035-2036')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('demand_notes', models.ManyToManyField(help_text='Demand notes consolidated into this query', related_name='ultimate_queries', to='inventory.demandnote')),
            ],
            options={
                'verbose_name': 'Ultimate Query',
                'verbose_name_plural': 'Ultimate Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UltimateQueryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField()),
                ('estimated_rate', models.DecimalField(decimal_places=2, help_text='Rate at time of query generation', max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('ultimate_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.ultimatequery')),
            ],
            options={
                'verbose_name': 'Ultimate Query Item',
                'verbose_name_plural': 'Ultimate Query Items',
                'unique_together': {('ultimate_query', 'item')},
            },
        ),
    ]
